# Generated by Django 4.2 on 2025-01-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.png', upload_to='blogs/'),
            preserve_default=False,
        ),
    ]
